[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [".venv", "venv", "build", "dist", ".git", "__pycache__"]

[tool.ruff.lint]
# Reglas comunes: pycodestyle/pyflakes (E,F), import order (I), modernización (UP), bugbear (B)
select = ["E", "F", "I", "UP", "B"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["app"]  # porque tu paquete está en src/app
